resource_types:
#- name: artifactory-resource
#  type: docker-image
#  source:
#    repository: springio/artifactory-resource
#    tag: 0.0.4
resources:
- name: git-repo
  type: git
  source:
    uri: ((github-repo))
    branch: ((branch))
    ignore_paths: ["ci/images/*"]
- name: ci-image
  type: docker-image
  source:
    repository: openjdk
#- name: artifactory-repo
#  type: artifactory-resource
#  source:
#    uri: ((artifactory-server))
#    username: ((artifactory-username))
#    password: ((artifactory-password))
#    build_name: ((build-name))
jobs:
- name: build
  serial: true
  plan:
  - get: git-repo
    trigger: true
  - get: ci-image
    version:
      digest: sha256:1b842a215cf3437c9197f0f47e5c1a12f0a27aed27b84536ee3d8ef6b9b7e19e
  - task: build-project
    image: ci-image
    file: git-repo/ci/tasks/build-project.yml
#  - put: artifactory-repo
#    params: &artifactory-params
#      repo: libs-snapshot-local
#      folder: distribution-repository
#      build_uri: "https://ci.spring.io/teams/${BUILD_TEAM_NAME}/pipelines/${BUILD_PIPELINE_NAME}/jobs/${BUILD_JOB_NAME}/builds/${BUILD_NAME}"
#      build_number: "${BUILD_PIPELINE_NAME}-${BUILD_JOB_NAME}-${BUILD_NAME}"
#      disable_checksum_uploads: true
